apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: leadbook_application
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.generic_app.updateStrategy }}
  strategy: {{- toYaml .Values.generic_app.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: leadbook_application
  template:
    metadata:
      {{- if .Values.generic_app.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: leadbook_application
        {{- if .Values.generic_app.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "generic.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.generic_app.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.generic_app.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.generic_app.podAffinityPreset "component" "leadbook_application" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.generic_app.podAntiAffinityPreset "component" "leadbook_application" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.generic_app.nodeAffinityPreset.type "key" .Values.generic_app.nodeAffinityPreset.key "values" .Values.generic_app.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.generic_app.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.generic_app.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.generic_app.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.generic_app.priorityClassName }}
      priorityClassName: {{ .Values.generic_app.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.generic_app.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.generic_app.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: {{ template "generic.image" . }}
          imagePullPolicy: {{ .Values.generic_app.image.pullPolicy }}
          {{- if .Values.generic_app.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.generic_app.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.generic_app.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.generic_app.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.generic_app.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: foo
              value: bar
            {{- if .Values.generic_app.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.generic_app.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.generic_app.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.generic_app.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.generic_app.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.generic_app.resources }}
          resources: {{- toYaml .Values.generic_app.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.generic_app.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.generic_app.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.generic_app.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.generic_app.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.generic_app.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.generic_app.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.generic_app.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
