{{- $top := . -}}
{{ range .Values.components -}}
{{- $comp := merge dict (deepCopy $top.Values.podDefaults) (deepCopy $top.Values.componentDefaults) . -}}
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" $top }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" $top }}-{{ $comp.name }}
  namespace: {{ $top.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $top | nindent 4 }}
    app.kubernetes.io/component: {{ $comp.name }}
    {{- if $top.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $top.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $top.Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" (dict "value" $top.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $comp.replicaCount }}
  {{- if $comp.updateStrategy }}
  strategy: {{- toYaml $comp.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $top | nindent 6 }}
      app.kubernetes.io/component: {{ $comp.name }}
  template:
    metadata:
      {{- if $comp.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" $comp.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" $top | nindent 8 }}
        app.kubernetes.io/component: {{ $comp.name }}
        {{- if $comp.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" $comp.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "images" (list $comp.image) "global" $top.Values.global) | nindent 6 -}}
      {{- if $comp.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $comp.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $comp.podAffinityPreset "component" $comp.name "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $comp.podAntiAffinityPreset "component" $comp.name "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $comp.nodeAffinityPreset.type "key" $comp.nodeAffinityPreset.key "values" $comp.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if $comp.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" $comp.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $comp.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" $comp.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if $comp.priorityClassName }}
      priorityClassName: {{ $comp.priorityClassName | quote }}
      {{- end }}
      {{- if $comp.podSecurityContext.enabled }}
      securityContext: {{- omit $comp.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $comp.name }}
          image: {{ include "common.images.image" (dict "imageRoot" $comp.image "global" $top.Values.global) }}
          imagePullPolicy: {{ $comp.image.pullPolicy }}
          {{- if $comp.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" $comp.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if $comp.containerSecurityContext.enabled }}
          securityContext: {{- omit $comp.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if $comp.command }}
          command: {{- include "common.tplvalues.render" (dict "value" $comp.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if $comp.args }}
          args: {{- include "common.tplvalues.render" (dict "value" $comp.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if $comp.ports }}
          ports: {{- toYaml $comp.ports | nindent 12 }}
          {{- end}}
          env:
            {{- if $comp.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" $comp.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- range $comp.extraEnvVarsCMs }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- range $comp.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
          {{- if $comp.resources }}
          resources: {{- toYaml $comp.resources | nindent 12 }}
          {{- end }}
          {{- if $comp.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit $comp.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if $comp.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" $comp.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if $comp.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit $comp.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if $comp.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" $comp.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
{{ end -}}
