{{ $top := . -}}
{{ range .Values.components -}}
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" $top }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" $top }}-{{ .name }}
  namespace: {{ $top.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $top | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
    {{- if $top.Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" $top.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $top.Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" $top.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .replicaCount }}
  {{- if .updateStrategy }}
  strategy: {{- toYaml .updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $top | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      {{- if .podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" $top | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
        {{- if .podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "images" (list .image) "global" $top.Values.global) -}}
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .podAffinityPreset "component" .name "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .podAntiAffinityPreset "component" .name "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .nodeAffinityPreset.type "key" .nodeAffinityPreset.key "values" .nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $top) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName | quote }}
      {{- end }}
      {{- if .podSecurityContext.enabled }}
      securityContext: {{- omit .podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ include "common.images.image" (dict "imageRoot" .image "global" $top.Values.global) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .containerSecurityContext.enabled }}
          securityContext: {{- omit .containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .command }}
          command: {{- include "common.tplvalues.render" (dict "value" .command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args: {{- include "common.tplvalues.render" (dict "value" .args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .ports }}
          ports: {{- toYaml .ports | nindent 12 }}
          {{- end}}
          env:
            - name: foo
              value: bar
            {{- if .extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .resources }}
          resources: {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
{{ end -}}
